### ISSUE TITLE
Dictionary does not contain all results

### ISSUE THREAD

**Issue by bbbrandyn** [imperial-qore/pyJMT#1]
When attempting to view the output metrics as a dictionary, only the latest one will show.

```
model.addMetric(openclass, queue, jmt.Metrics.RESPONSE_TIME)  
model.addMetric(openclass, queue, jmt.Metrics.QUEUE_TIME)  
model.addMetric(openclass, queue, jmt.Metrics.UTILIZATION)  
results_dict = model.getResults()  
print(results_dict["myQueue"])
```

Output:

` {'Class1': {'meanValue': '0.496953737041098', 'nodeType': 'station', 'precision': '0.03', 'alfa': '0.01', 'analyzedSamples': '46080', 'measureType': 'Utilization', 'successful': 'true', 'discardedSamples': '630', 'maxSamples': '1000000', 'upperLimit': '0.5090235375229217', 'lowerLimit': '0.48488393655927425'}} `

I can only view utilization which was the last metric added

**Comment by gcasale** [comment]
Thank you - we will look into this. Could you please share the full script?

**Comment by gcasale** [comment]
This should now be fixed by the last commit.

**Comment by gcasale** [comment]
Fixed
